// audit/smoke_icalendar_microcopy.test.mjs
//
// Regression tests for the issue #581 iCalendar microcopy gate.
// The probe walks internal/archive/export_service.go for the
// canonical iCalendar copy (calname, PRODID, SUMMARY presets,
// DESCRIPTION lines, VALARM bodies) and asserts each required
// substring is present in the current repo (GREEN-on-HEAD;
// the slice is audit-only). This test file pins the GREEN state
// plus synthetic regressions for each rule family.

import { strict as assert } from 'node:assert';
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1');
const PROBE = join(ROOT, 'audit/smoke_icalendar_microcopy.mjs');
const SOURCE = join(ROOT, 'internal/archive/export_service.go');

let pass = 0;
let fail = 0;

function test(name, fn) {
  try {
    fn();
    pass++;
    console.log(`  PASS ${name}`);
  } catch (err) {
    fail++;
    console.log(`  FAIL ${name}`);
    console.log(`    ${err.message}`);
  }
}

function runProbe(source = SOURCE, strict = false) {
  return spawnSync('node', [PROBE, ...(strict ? ['--strict'] : [])], {
    encoding: 'utf8',
    env: { ...process.env, ICS_SOURCE: source },
  });
}

// Synthetic fixtures are a single .go file dropped into a temp
// dir; the probe walks it via ICS_SOURCE. Each fixture contains
// the canonical strings OR is missing them, depending on the
// test intent. The file is named "export_service.go" so the
// synthetic reads as if it were the real producer; the probe
// only checks for substrings, so the file does not need to
// compile.

function withTempSource(body, fn) {
  const dir = mkdtempSync(join(tmpdir(), 'ical-microcopy-'));
  const source = join(dir, 'export_service.go');
  writeFileSync(source, body);
  try {
    return fn(source);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const CANONICAL_SOURCE = [
  '// canonical iCalendar producer -- every pinned string present',
  'package archive',
  '',
  'import (',
  '  "fmt"',
  '  "time"',
  ')',
  '',
  'const canonicalCALNAME = "X-WR-CALNAME:DixieData Memorial Anniversaries"',
  'const canonicalPRODID = "Memorial Anniversaries v%d"',
  '',
  'func iCalendarManagedSummary(displayName string, preset int) string {',
  '  switch preset {',
  '  case 0:',
  '    return displayName + " Memorial Anniversary"',
  '  case 1:',
  '    return "D-001" + " " + string(0x2022) + " " + displayName',
  '  default:',
  '    return "Memorial Anniversary: " + displayName',
  '  }',
  '}',
  '',
  'func iCalendarManagedDescriptionLines(displayID string, unit string, buriedIn string, deathDate string) []string {',
  '  lines := []string{}',
  '  lines = append(lines, "Record ID: " + displayID)',
  '  lines = append(lines, "Unit: " + unit)',
  '  lines = append(lines, "Buried In: " + buriedIn)',
  '  lines = append(lines, "Original Death Date: " + deathDate)',
  '  lines = append(lines, "Generated by DixieData.")',
  '  return lines',
  '}',
  '',
  'func iCalendarAlarmLines(displayName string, minutes int) string {',
  '  if minutes <= 60 {',
  '    return "Memorial anniversary in one hour for " + displayName',
  '  }',
  '  return "Upcoming memorial anniversary for " + displayName',
  '}',
  '',
  'var _ = fmt.Sprintf',
  'var _ = time.Now',
].join('\n');

// --- baseline-on-HEAD --------------------------------------------------

test('probe reports 0 baseline findings on current repo (GREEN-on-HEAD)', () => {
  const result = runProbe(SOURCE, false);
  assert.equal(result.status, 0, `expected informational exit 0\nstdout: ${result.stdout}`);
  assert.match(
    result.stdout,
    /Required copy findings: 0/,
    `expected 0 required findings on HEAD (post-fix baseline); got:\n${result.stdout}`,
  );
  assert.match(
    result.stdout,
    /Forbidden\/verbose copy findings: 0/,
    `expected 0 forbidden findings on HEAD; got:\n${result.stdout}`,
  );
});

test('probe exits 0 under --strict on current repo (GREEN-on-HEAD)', () => {
  const result = runProbe(SOURCE, true);
  assert.equal(result.status, 0, `expected strict exit 0 on HEAD\nstdout: ${result.stdout}`);
  assert.match(result.stdout, /iCalendar microcopy sweep: clean/);
});

test('probe summary present on HEAD', () => {
  const result = runProbe(SOURCE, false);
  assert.match(result.stdout, /File scanned:/);
  assert.match(result.stdout, /Total findings: 0/);
});

// --- synthetic positive: missing-calname fixture -----------------------

test('synthetic missing-calname fixture fails the required rule', () => {
  withTempSource(
    CANONICAL_SOURCE.replace(
      'X-WR-CALNAME:DixieData Memorial Anniversaries',
      'X-WR-CALNAME:Holiday Calendar',
    ),
    (source) => {
      const result = runProbe(source, true);
      assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
      assert.match(result.stdout, /X-WR-CALNAME/);
    },
  );
});

// --- synthetic positive: forbidden drift fixtures ---------------------

test('synthetic Birthday-in-SUMMARY fixture fails the forbidden rule', () => {
  const drift = '\nconst driftBirthday = "SUMMARY:John Smith Birthday"\n';
  withTempSource(CANONICAL_SOURCE + drift, (source) => {
    const result = runProbe(source, true);
    assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
    assert.match(result.stdout, /Birthday/);
  });
});

test('synthetic Death-Anniversary-in-SUMMARY fixture fails the forbidden rule', () => {
  const drift = '\nconst driftDeathAnniversary = "SUMMARY:John Smith Death Anniversary"\n';
  withTempSource(CANONICAL_SOURCE + drift, (source) => {
    const result = runProbe(source, true);
    assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
    assert.match(result.stdout, /Death Anniversary/);
  });
});

test('synthetic Memorial-Day-for fixture fails the forbidden rule', () => {
  const drift = '\nconst driftMemorialDay = "Memorial Day for John Smith"\n';
  withTempSource(CANONICAL_SOURCE + drift, (source) => {
    const result = runProbe(source, true);
    assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
    assert.match(result.stdout, /Memorial Day for /);
  });
});

test('synthetic .ics-suffix-on-calname fixture fails the forbidden rule', () => {
  withTempSource(
    CANONICAL_SOURCE.replace(
      'X-WR-CALNAME:DixieData Memorial Anniversaries',
      'X-WR-CALNAME:DixieData Memorial Anniversaries.ics',
    ),
    (source) => {
      const result = runProbe(source, true);
      assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
      assert.match(result.stdout, /calname accidentally appended/);
    },
  );
});

// --- synthetic positive: missing DESCRIPTION line ----------------------

test('synthetic missing-Record-ID fixture fails the required rule', () => {
  withTempSource(
    CANONICAL_SOURCE.replace('"Record ID: "', '"RID: "'),
    (source) => {
      const result = runProbe(source, true);
      assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
      assert.match(result.stdout, /DESCRIPTION Record ID/);
    },
  );
});

test('synthetic missing-Unit fixture fails the required rule', () => {
  withTempSource(
    CANONICAL_SOURCE.replace('"Unit: "', '"Served in: "'),
    (source) => {
      const result = runProbe(source, true);
      assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
      assert.match(result.stdout, /DESCRIPTION Unit/);
    },
  );
});

test('synthetic missing-Generated-By-DixieData fixture fails the required rule', () => {
  withTempSource(
    CANONICAL_SOURCE.replace('"Generated by DixieData."', '"Generated by your archive."'),
    (source) => {
      const result = runProbe(source, true);
      assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
      assert.match(result.stdout, /DESCRIPTION trailing attribution/);
    },
  );
});

// --- synthetic positive: missing VALARM body ---------------------------

test('synthetic missing-VALARM-default-body fixture fails the required rule', () => {
  withTempSource(
    CANONICAL_SOURCE.replace('"Upcoming memorial anniversary for "', '"Anniversary reminder for "'),
    (source) => {
      const result = runProbe(source, true);
      assert.equal(result.status, 1, `expected strict failure\nstdout: ${result.stdout}`);
      assert.match(result.stdout, /VALARM default-body/);
    },
  );
});

// --- synthetic positive: full canonical passes -------------------------

test('synthetic fully-canonical fixture passes the strict gate', () => {
  withTempSource(CANONICAL_SOURCE, (source) => {
    const result = runProbe(source, true);
    assert.equal(result.status, 0, `expected strict exit 0\nstdout: ${result.stdout}`);
  });
});

// --- strict mode -------------------------------------------------------

test('probe exits 0 without --strict even when findings exist', () => {
  const drift = '\nconst driftBirthday = "SUMMARY:John Smith Birthday"\n';
  withTempSource(CANONICAL_SOURCE + drift, (source) => {
    const result = runProbe(source, false);
    assert.equal(result.status, 0, `expected informational exit 0\nstdout: ${result.stdout}`);
    assert.match(result.stdout, /informational findings/);
  });
});

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
