// audit/smoke_icalendar_microcopy.mjs
//
// Issue #581 — iCalendar microcopy gate (audit-only slice 3).
//
// The .templ probe (audit/smoke_microcopy.mjs), the Static Archive
// probe (audit/smoke_static_archive_microcopy.mjs), and the Typst
// PDF probe (audit/smoke_pdf_microcopy.mjs) cover three export
// grammars; iCalendar has its own (RFC 5545). This probe walks the
// only Go file that emits iCalendar text —
// internal/archive/export_service.go — and pins the canonical
// user-facing copy verbatim. The probe exits 0 on HEAD (no edits
// planned; this slice locks the surface for future drift).
//
// Pinned strings (recon catalog):
//   - X-WR-CALNAME:DixieData Memorial Anniversaries
//   - PRODID:-//{AppName} v{AppVersion}//Memorial Anniversaries
//     v{N}//EN
//   - "{name} — Memorial Anniversary" SUMMARY format
//   - DESCRIPTION lines: "Record ID: ", "Unit: ", "Buried In: ",
//     "Original Death Date: ", "Generated by DixieData."
//   - VALARM body: "Upcoming memorial anniversary for ",
//     "Memorial anniversary in one hour for "
//
// Forbidden (must NOT appear): any drift away from these —
// "Birthday", "Death Anniversary", "Memorial Day for ", " event "
// in calname, non-"Memorial Anniversary" calname, length-truncated
// strings, etc.
//
// Skipped: machine-readable envelope extensions (X-DIXIEDATA-*),
// UID generation, the icalText() escape helper, byte-level
// writeICalendarLine, the CSV / JSON / JPG export paths.
//
// Usage:
//   node audit/smoke_icalendar_microcopy.mjs
//   node audit/smoke_icalendar_microcopy.mjs --strict
//
// Exit codes:
//   0  clean OR non-strict with findings printed
//   1  strict and at least one finding
//   2  fatal (couldn't read ICS_SOURCE)
//
// ICS_SOURCE exists for synthetic probe fixtures (mirrors the
// STATIC_ARCHIVE_SOURCE / PDF_SOURCE conventions from slices 1+2).

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1');
const SOURCE = process.env.ICS_SOURCE || join(ROOT, 'internal', 'archive', 'export_service.go');
const STRICT = process.argv.includes('--strict');

let source;
try {
  source = readFileSync(SOURCE, 'utf8');
} catch (err) {
  console.error(`fatal: cannot read ICS_SOURCE at ${SOURCE}: ${err.message}`);
  process.exit(2);
}

// Catalogue the required strings. Each tuple: [name, substring,
// hint]. The substring is matched against the file as a whole
// (raw Go source). Calendar-client conventions (iOS / Google /
// Apple) referenced in the hint, not enforced — the probe checks
// the producer side only.
const REQUIRED = [
  [
    'X-WR-CALNAME',
    'X-WR-CALNAME:DixieData Memorial Anniversaries',
    'calname (calendar display name) must remain "DixieData Memorial Anniversaries"',
  ],
  [
    'PRODID producer identifier',
    'Memorial Anniversaries v%d',
    'PRODID line includes the "Memorial Anniversaries v{N}" segment per RFC 5545 §3.7.3',
  ],
  [
    'SUMMARY NameLead literal',
    '" Memorial Anniversary"',
    'NameLead preset SUMMARY ends with the literal " Memorial Anniversary" (no em-dash, no trailing punctuation)',
  ],
  [
    'SUMMARY default preset prefix',
    '"Memorial Anniversary: "',
    'default preset SUMMARY uses the literal "Memorial Anniversary: " prefix',
  ],
  [
    'DESCRIPTION Record ID',
    'Record ID: ',
    'IncludeRecordID branch emits a "Record ID: " DESCRIPTION line',
  ],
  [
    'DESCRIPTION Unit',
    'Unit: ',
    'IncludeUnit branch emits a "Unit: " DESCRIPTION line',
  ],
  [
    'DESCRIPTION Buried In',
    'Buried In: ',
    'IncludeBuriedIn branch emits a "Buried In: " DESCRIPTION line',
  ],
  [
    'DESCRIPTION Original Death Date',
    'Original Death Date: ',
    'IncludeOriginalDate branch emits an "Original Death Date: " DESCRIPTION line',
  ],
  [
    'DESCRIPTION trailing attribution',
    'Generated by DixieData.',
    'trailing DESCRIPTION attribution; preserved per user direction (slice 3 audit-only)',
  ],
  [
    'VALARM default-body prefix',
    'Upcoming memorial anniversary for ',
    'default VALARM body uses "Upcoming memorial anniversary for {name}"',
  ],
  [
    'VALARM hour-body prefix',
    'Memorial anniversary in one hour for ',
    'sub-hour VALARM body uses "Memorial anniversary in one hour for {name}"',
  ],
];

// Forbidden patterns — drift signposts. Each tuple: [name, regex,
// hint]. The probe does NOT block calendar-client rephrasing of
// the VALARM body (RFC 5545 leaves that to clients) — only the
// producer-side strings.
const FORBIDDEN = [
  [
    'calname drift (not DixieData Memorial Anniversaries)',
    /X-WR-CALNAME:(?!DixieData Memorial Anniversaries\b)/,
    'any X-WR-CALNAME that is NOT exactly "DixieData Memorial Anniversaries" is drift',
  ],
  [
    'non-glossary "Birthday" in SUMMARY',
    /SUMMARY.*Birthday/,
    'SUMMARY must use "Memorial Anniversary", never "Birthday"',
  ],
  [
    'non-glossary "Death Anniversary" in SUMMARY',
    /SUMMARY.*Death Anniversary/,
    'SUMMARY must use "Memorial Anniversary", never "Death Anniversary"',
  ],
  [
    'non-glossary "Memorial Day for " phrasing',
    /Memorial Day for /,
    'alarm/SUMMARY must not use "Memorial Day for"; the canonical phrasing is "Memorial Anniversary"',
  ],
  [
    'calname accidentally appended ".ics"',
    /X-WR-CALNAME:DixieData Memorial Anniversaries\.ics/,
    'calname accidentally appended ".ics" suffix — would break calendar import',
  ],
];

const findings = [];
for (const [name, substring, hint] of REQUIRED) {
  if (!source.includes(substring)) {
    findings.push({ rule: 'required', name, text: substring, hint });
  }
}
for (const [name, pattern, hint] of FORBIDDEN) {
  if (pattern.test(source)) {
    findings.push({ rule: 'forbidden', name, text: String(pattern), hint });
  }
}

const byRule = { required: 0, forbidden: 0 };
for (const finding of findings) byRule[finding.rule]++;

console.log(`File scanned: ${SOURCE}`);
console.log(`  Required copy findings: ${byRule.required}`);
console.log(`  Forbidden/verbose copy findings: ${byRule.forbidden}`);
console.log(`Total findings: ${findings.length}`);

if (findings.length) {
  console.log('');
  console.log('=== findings ===');
  for (const finding of findings) {
    console.log(`  ${finding.rule.padEnd(10)}  ${finding.name}`);
    console.log(`              ${finding.text}`);
    console.log(`              → ${finding.hint}`);
  }
}

if (STRICT && findings.length) {
  console.log('');
  console.log('--strict: treating as a CI failure.');
  process.exit(1);
}

console.log(findings.length ? '\niCalendar microcopy sweep: informational findings.' : '\niCalendar microcopy sweep: clean.');
process.exit(0);
