package appshell

import (
	"os/exec"
	"strings"
	"testing"
)

// TestDebugBuildArtifactsHaveSymbolsAndDevToolsHooks is the
// regression net for the make-debug build pipeline (scripts/
// build-common.ps1 Invoke-DixieDataBuild -DebugBuild + scripts/
// build-debug.ps1).
//
// The user-reported failure mode was: "make debug" produced a
// binary indistinguishable from make release. -trimpath
// stripped source paths, so dlv attach could not set
// breakpoints; the Wails WebView2 had no DevTools because the
// -debug flag was never passed. This test pins down three
// observable properties of the build artifact:
//
//  1. The build/bin/DixieData.exe binary exists and reports
//     symbols for an appshell source line (proves -trimpath
//     was NOT applied — the path appears in the symbol table).
//  2. go tool nm reports a non-trivial symbol count (proves
//     -gcflags=-N -l did not elide every frame; if the symbol
//     table were empty the optimiser would have stripped
//     everything).
//  3. The Run-DixieData-Debug.ps1 launcher sets the
//     DIXIEDATA_DEVTOOLS env var (proves the launcher was
//     regenerated by the updated Write-DixieDataDebugLauncher
//     helper).
//
// The test skips when build/bin/DixieData.exe is absent
// (release-only CI run) so it doesn't fail unrelated pipelines.
func TestDebugBuildArtifactsHaveSymbolsAndDevToolsHooks(t *testing.T) {
	exePath := findDebugBinary(t)
	if exePath == "" {
		t.Skip("build/bin/DixieData.exe not present; run `make debug` first")
	}

	// Property 1: source paths survive in the symbol table.
	// go tool nm lists every defined symbol. Filter for any
	// appshell symbol whose address maps back to a Go source
	// line (the tool prefixes addresses; we look for the
	// module path "valueforvalue/DixieData/internal/appshell"
	// which only appears when DWARF debug info is present).
	out := nmOutput(t, exePath)
	if !strings.Contains(out, "valueforvalue/DixieData/internal/appshell") {
		t.Errorf("debug binary is missing DWARF source paths; -trimpath slipped back in?\nfirst 200 nm lines:\n%s", firstLines(out, 200))
	}

	// Property 2: symbol table is non-trivial. A stripped or
	// trimpath'd binary still has runtime symbols, but the
	// count drops below 10k. A debug build is 40-50k symbols.
	symbolCount := strings.Count(out, "\n")
	if symbolCount < 10000 {
		t.Errorf("debug binary has only %d symbols; expected 10k+ for a debug build", symbolCount)
	}

	// Property 3: the launcher sets DIXIEDATA_DEVTOOLS=1 so the
	// app's EnableDefaultContextMenu env-gate in main.go opens
	// the WebView2 DevTools even on a release binary.
	launcherPath := exePath[:len(exePath)-len("DixieData.exe")] + "Run-DixieData-Debug.ps1"
	launcher, err := exec.Command("powershell", "-NoProfile", "-Command", "Get-Content -Path '"+launcherPath+"' -Raw").Output()
	if err != nil {
		t.Fatalf("read launcher: %v", err)
	}
	if !strings.Contains(string(launcher), "DIXIEDATA_DEVTOOLS") {
		t.Errorf("Run-DixieData-Debug.ps1 does not set DIXIEDATA_DEVTOOLS; the launcher helper was not regenerated\nlauncher:\n%s", string(launcher))
	}
}

// findDebugBinary looks for build/bin/DixieData.exe relative to
// the repository root. Returns "" when missing so callers can
// skip cleanly.
func findDebugBinary(t *testing.T) string {
	t.Helper()
	root := repoRoot(t)
	candidates := []string{
		root + "/build/bin/DixieData.exe",
		root + "/build/bin/DixieData",
	}
	for _, p := range candidates {
		if _, err := exec.Command("test", "-f", p).Output(); err == nil {
			return p
		}
	}
	return ""
}

// nmOutput runs `go tool nm` against the given binary and
// returns stdout. Stdout is intentionally uncapped because the
// caller asserts on substring presence.
func nmOutput(t *testing.T, exePath string) string {
	t.Helper()
	cmd := exec.Command("go", "tool", "nm", exePath)
	out, err := cmd.Output()
	if err != nil {
		stderr := ""
		if ee, ok := err.(*exec.ExitError); ok {
			stderr = string(ee.Stderr)
		}
		t.Fatalf("go tool nm %s: %v\nstderr: %s", exePath, err, stderr)
	}
	return string(out)
}

// firstLines returns the first n lines of s, useful for keeping
// failure messages readable when the underlying string is huge.
func firstLines(s string, n int) string {
	lines := strings.Split(s, "\n")
	if len(lines) <= n {
		return s
	}
	return strings.Join(lines[:n], "\n")
}

// repoRoot walks up from the working directory until it finds
// the DixieData go.mod so the test passes regardless of the
// cwd the user invokes it from.
func repoRoot(t *testing.T) string {
	t.Helper()
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Dir}}")
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("go list -m: %v", err)
	}
	root := strings.TrimSpace(string(out))
	if root == "" {
		t.Fatalf("could not resolve module root")
	}
	return root
}