package services

import (
	"archive/zip"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
	"github.com/valueforvalue/DixieData/internal/db"
	"github.com/valueforvalue/DixieData/internal/models"
)

const exportBatchSize = 500

type ExportService struct {
	db      *db.DB
	soldier *SoldierService
}

func NewExportService(database *db.DB, soldier *SoldierService) *ExportService {
	return &ExportService{db: database, soldier: soldier}
}

// ExportJSON streams a full hierarchical export (Soldier -> Records -> Images)
// to outputPath in JSON array format, processing records in batches to avoid
// loading the entire dataset into memory at once.
func (e *ExportService) ExportJSON(outputPath string) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")

	if _, err := fmt.Fprint(f, "[\n"); err != nil {
		return err
	}

	first := true
	page := 1
	for {
		batch, _, err := e.soldier.List(page, exportBatchSize)
		if err != nil {
			return err
		}
		if len(batch) == 0 {
			break
		}

		for _, s := range batch {
			enriched, err := e.soldier.GetByID(s.ID)
			if err != nil {
				return err
			}
			if !first {
				if _, err := fmt.Fprint(f, ",\n"); err != nil {
					return err
				}
			}
			if err := enc.Encode(enriched); err != nil {
				return err
			}
			first = false
		}

		if len(batch) < exportBatchSize {
			break
		}
		page++
	}

	_, err = fmt.Fprint(f, "]\n")
	return err
}

func (e *ExportService) ExportICalendar(outputPath string) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	soldiers, err := exportSoldiers(e.soldier)
	if err != nil {
		return err
	}

	now := time.Now()
	for _, line := range []string{
		"BEGIN:VCALENDAR",
		"VERSION:2.0",
		"PRODID:-//DixieData//Anniversaries//EN",
		"CALSCALE:GREGORIAN",
		"METHOD:PUBLISH",
		"X-WR-CALNAME:DixieData Anniversaries",
	} {
		if err := writeICalendarLine(f, line); err != nil {
			return err
		}
	}

	for _, soldier := range soldiers {
		if soldier.DeathMonth < 1 || soldier.DeathDay < 1 {
			continue
		}
		start := nextGoogleAnniversaryDate(soldier, now)
		start = time.Date(start.Year(), start.Month(), start.Day(), 9, 0, 0, 0, time.Local)
		end := start.Add(time.Hour)
		description := fmt.Sprintf("Database Number: %s\nUnit: %s\nBuried In: %s\nOriginal Death Date: %s\nGenerated by DixieData.",
			soldier.DisplayID,
			soldier.Unit,
			soldier.BuriedIn,
			soldierDeathLine(soldier),
		)

		lines := []string{
			"BEGIN:VEVENT",
			fmt.Sprintf("UID:%s", icalText("dixiedata-"+strings.ToLower(soldier.DisplayID)+"@dixiedata.local")),
			fmt.Sprintf("DTSTAMP:%s", now.Format("20060102T150405Z")),
			fmt.Sprintf("SUMMARY:%s", icalText("DixieData Anniversary: "+soldierDisplayName(soldier))),
			fmt.Sprintf("DESCRIPTION:%s", icalText(description)),
			fmt.Sprintf("DTSTART:%s", start.Format("20060102T150405")),
			fmt.Sprintf("DTEND:%s", end.Format("20060102T150405")),
			"RRULE:FREQ=YEARLY",
			"STATUS:CONFIRMED",
			"TRANSP:TRANSPARENT",
			"BEGIN:VALARM",
			"TRIGGER:-P1D",
			"ACTION:DISPLAY",
			fmt.Sprintf("DESCRIPTION:%s", icalText("Upcoming anniversary for "+soldierDisplayName(soldier))),
			"END:VALARM",
			"BEGIN:VALARM",
			"TRIGGER:-PT1H",
			"ACTION:DISPLAY",
			fmt.Sprintf("DESCRIPTION:%s", icalText("Anniversary in one hour for "+soldierDisplayName(soldier))),
			"END:VALARM",
			"END:VEVENT",
		}
		for _, line := range lines {
			if err := writeICalendarLine(f, line); err != nil {
				return err
			}
		}
	}

	return writeICalendarLine(f, "END:VCALENDAR")
}

// ExportCSV streams a flat CSV export of all soldiers, processing records in
// batches to avoid loading the entire dataset into memory at once.
func (e *ExportService) ExportCSV(outputPath string) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	w := csv.NewWriter(f)
	defer w.Flush()

	header := []string{"id", "display_id", "is_generated", "first_name", "middle_name", "last_name", "rank", "rank_in", "rank_out", "unit", "pension_state", "death_year", "death_month", "death_day", "birth_info", "buried_in", "notes", "created_at"}
	if err := w.Write(header); err != nil {
		return err
	}

	page := 1
	for {
		batch, _, err := e.soldier.List(page, exportBatchSize)
		if err != nil {
			return err
		}
		if len(batch) == 0 {
			break
		}

		for _, s := range batch {
			row := []string{
				fmt.Sprintf("%d", s.ID),
				s.DisplayID,
				fmt.Sprintf("%v", s.IsGenerated),
				s.FirstName,
				s.MiddleName,
				s.LastName,
				s.Rank,
				s.RankIn,
				s.RankOut,
				s.Unit,
				s.PensionState,
				fmt.Sprintf("%d", s.DeathYear),
				fmt.Sprintf("%d", s.DeathMonth),
				fmt.Sprintf("%d", s.DeathDay),
				s.BirthInfo,
				s.BuriedIn,
				s.Notes,
				s.CreatedAt,
			}
			if err := w.Write(row); err != nil {
				return err
			}
		}
		w.Flush()
		if err := w.Error(); err != nil {
			return err
		}

		if len(batch) < exportBatchSize {
			break
		}
		page++
	}
	return nil
}

func (e *ExportService) ExportImages(outputPath string, images []models.Image) error {
	f, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer f.Close()

	zipWriter := zip.NewWriter(f)
	defer zipWriter.Close()

	for _, image := range images {
		source, err := os.Open(image.FilePath)
		if err != nil {
			return err
		}

		entryName := image.FileName
		if entryName == "" {
			entryName = filepath.Base(image.FilePath)
		}

		entry, err := zipWriter.Create(entryName)
		if err != nil {
			source.Close()
			return err
		}

		if _, err := io.Copy(entry, source); err != nil {
			source.Close()
			return err
		}
		source.Close()
	}

	return nil
}

func (e *ExportService) ExportSoldierPDF(outputPath string, soldier models.Soldier) error {
	pdf := newPDFDocument()
	pdf.AddPage()

	pdf.SetFont("Times", "B", 20)
	pdf.CellFormat(0, 12, soldierDisplayName(soldier), "", 1, "", false, 0, "")
	pdf.SetFont("Times", "", 12)
	pdf.CellFormat(0, 8, fmt.Sprintf("Database Number: %s", soldier.DisplayID), "", 1, "", false, 0, "")
	pdf.Ln(2)

	writePDFField(pdf, "Rank In", soldier.RankIn)
	writePDFField(pdf, "Rank Out", displaySoldierRank(soldier))
	writePDFField(pdf, "Unit", soldier.Unit)
	writePDFField(pdf, "Pension State", soldier.PensionState)
	writePDFField(pdf, "Death", soldierDeathLine(soldier))
	writePDFField(pdf, "Birth Info", soldier.BirthInfo)
	writePDFField(pdf, "Buried In", soldier.BuriedIn)
	writePDFSection(pdf, "Notes")
	writePDFBody(pdf, soldier.Notes)

	if len(soldier.Records) > 0 {
		writePDFSection(pdf, "Records")
		for _, record := range soldier.Records {
			line := record.RecordType
			if strings.TrimSpace(record.AppID) != "" {
				line += fmt.Sprintf(" (App: %s)", record.AppID)
			}
			writePDFBullet(pdf, line)
			if strings.TrimSpace(record.Details) != "" {
				writePDFBody(pdf, record.Details)
			}
		}
	}

	if len(soldier.Images) > 0 {
		writePDFSection(pdf, "Images")
		for _, image := range soldier.Images {
			writePDFImageRow(pdf, image)
		}
	}

	return pdf.OutputFileAndClose(outputPath)
}

func (e *ExportService) ExportMonthlyAnniversaryPDF(outputPath string, month int, calendar map[int][]models.Soldier) error {
	pdf := newPDFDocument()
	pdf.AddPage()

	title := fmt.Sprintf("%s Anniversary Report", monthLabel(month))
	pdf.SetFont("Times", "B", 20)
	pdf.CellFormat(0, 12, title, "", 1, "", false, 0, "")
	pdf.SetFont("Times", "", 12)
	pdf.CellFormat(0, 8, "Includes soldier names and database numbers for the selected month.", "", 1, "", false, 0, "")
	pdf.Ln(2)

	days := make([]int, 0, len(calendar))
	for day := range calendar {
		if day == 0 {
			continue
		}
		days = append(days, day)
	}
	sort.Ints(days)

	if len(days) == 0 {
		writePDFBody(pdf, "No soldiers are recorded for this month.")
		return pdf.OutputFileAndClose(outputPath)
	}

	for _, day := range days {
		soldiers := append([]models.Soldier(nil), calendar[day]...)
		sort.Slice(soldiers, func(i, j int) bool {
			left := strings.ToLower(soldierDisplayName(soldiers[i]))
			right := strings.ToLower(soldierDisplayName(soldiers[j]))
			return left < right
		})

		writePDFSection(pdf, fmt.Sprintf("%s %d", monthLabel(month), day))
		for _, soldier := range soldiers {
			writePDFBullet(pdf, fmt.Sprintf("%s - %s", soldierDisplayName(soldier), soldier.DisplayID))
		}
	}

	return pdf.OutputFileAndClose(outputPath)
}

func newPDFDocument() *fpdf.Fpdf {
	pdf := fpdf.New("P", "mm", "Letter", "")
	pdf.SetTitle("DixieData Report", false)
	pdf.SetAuthor("DixieData", false)
	pdf.SetMargins(16, 16, 16)
	pdf.SetAutoPageBreak(true, 16)
	pdf.SetCompression(false)
	return pdf
}

func exportSoldiers(soldierSvc *SoldierService) ([]models.Soldier, error) {
	var all []models.Soldier
	page := 1
	for {
		batch, _, err := soldierSvc.List(page, exportBatchSize)
		if err != nil {
			return nil, err
		}
		if len(batch) == 0 {
			break
		}
		all = append(all, batch...)
		if len(batch) < exportBatchSize {
			break
		}
		page++
	}
	sort.Slice(all, func(i, j int) bool {
		return strings.ToLower(all[i].DisplayID) < strings.ToLower(all[j].DisplayID)
	})
	return all, nil
}

func icalText(value string) string {
	replacer := strings.NewReplacer(
		"\\", "\\\\",
		";", "\\;",
		",", "\\,",
		"\r\n", "\\n",
		"\n", "\\n",
	)
	return replacer.Replace(strings.TrimSpace(value))
}

func nextAnniversaryDate(soldier models.Soldier, now time.Time) time.Time {
	year := now.Year()
	for i := 0; i < 8; i++ {
		candidateYear := year + i
		candidate := time.Date(candidateYear, time.Month(soldier.DeathMonth), soldier.DeathDay, 0, 0, 0, 0, time.UTC)
		if candidate.Month() != time.Month(soldier.DeathMonth) || candidate.Day() != soldier.DeathDay {
			continue
		}
		if !candidate.Before(time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)) {
			return candidate
		}
	}
	return time.Date(now.Year(), time.Month(soldier.DeathMonth), soldier.DeathDay, 0, 0, 0, 0, time.UTC)
}

func writeICalendarLine(w io.Writer, line string) error {
	const maxLineLength = 75
	for len(line) > maxLineLength {
		if _, err := fmt.Fprintf(w, "%s\r\n ", line[:maxLineLength]); err != nil {
			return err
		}
		line = line[maxLineLength:]
	}
	_, err := fmt.Fprintf(w, "%s\r\n", line)
	return err
}

func writePDFSection(pdf *fpdf.Fpdf, title string) {
	pdf.Ln(4)
	pdf.SetFont("Times", "B", 15)
	pdf.CellFormat(0, 8, title, "", 1, "", false, 0, "")
	pdf.SetFont("Times", "", 12)
}

func writePDFField(pdf *fpdf.Fpdf, label, value string) {
	pdf.SetFont("Times", "B", 12)
	pdf.CellFormat(34, 8, label+":", "", 0, "", false, 0, "")
	pdf.SetFont("Times", "", 12)
	pdf.MultiCell(0, 8, emptyPDFValue(value), "", "", false)
}

func writePDFBody(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Times", "", 12)
	pdf.MultiCell(0, 7, emptyPDFValue(text), "", "", false)
}

func writePDFBullet(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Times", "", 12)
	pdf.CellFormat(6, 7, "-", "", 0, "", false, 0, "")
	pdf.MultiCell(0, 7, emptyPDFValue(text), "", "", false)
}

func writePDFImageRow(pdf *fpdf.Fpdf, image models.Image) {
	const thumbnailWidth = 34.0
	const rowHeight = 36.0

	_, pageHeight := pdf.GetPageSize()
	if pdf.GetY()+rowHeight > pageHeight-16 {
		pdf.AddPage()
	}

	x := pdf.GetX()
	y := pdf.GetY()
	imagePath := imagePathForPDF(image)

	if imagePath != "" {
		pdf.ImageOptions(imagePath, x, y, thumbnailWidth, 0, false, fpdf.ImageOptions{
			ImageType: strings.TrimPrefix(strings.ToLower(filepath.Ext(imagePath)), "."),
		}, 0, "")
	} else {
		pdf.Rect(x, y, thumbnailWidth, 22, "D")
	}

	pdf.SetXY(x+thumbnailWidth+4, y)
	title := image.FileName
	if strings.TrimSpace(image.Caption) != "" {
		title = fmt.Sprintf("%s - %s", image.FileName, image.Caption)
	}
	pdf.SetFont("Times", "", 12)
	pdf.MultiCell(0, 6, emptyPDFValue(title), "", "", false)
	pdf.SetXY(x+thumbnailWidth+4, y+10)
	pdf.MultiCell(0, 6, "DB Path: "+emptyPDFValue(image.FilePath), "", "", false)
	pdf.SetXY(x+thumbnailWidth+4, y+18)
	pdf.MultiCell(0, 6, "Full Path: "+emptyPDFValue(strings.TrimSpace(image.ResolvedPath)), "", "", false)

	if pdf.GetY() < y+rowHeight {
		pdf.SetY(y + rowHeight)
	}
}

func emptyPDFValue(value string) string {
	if strings.TrimSpace(value) == "" {
		return "Not recorded"
	}
	return value
}

func soldierDisplayName(soldier models.Soldier) string {
	return strings.TrimSpace(strings.TrimSpace(displaySoldierRank(soldier)) + " " + soldierFullName(soldier))
}

func soldierFullName(soldier models.Soldier) string {
	return strings.Join(compactNameParts(soldier.FirstName, soldier.MiddleName, soldier.LastName), " ")
}

func displaySoldierRank(soldier models.Soldier) string {
	if strings.TrimSpace(soldier.RankOut) != "" {
		return strings.TrimSpace(soldier.RankOut)
	}
	if strings.TrimSpace(soldier.Rank) != "" {
		return strings.TrimSpace(soldier.Rank)
	}
	return strings.TrimSpace(soldier.RankIn)
}

func compactNameParts(parts ...string) []string {
	result := make([]string, 0, len(parts))
	for _, part := range parts {
		if trimmed := strings.TrimSpace(part); trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}

func soldierDeathLine(soldier models.Soldier) string {
	if soldier.DeathMonth == 0 && soldier.DeathYear == 0 {
		return ""
	}
	if soldier.DeathMonth == 0 {
		return fmt.Sprintf("%d", soldier.DeathYear)
	}
	if soldier.DeathDay > 0 {
		return fmt.Sprintf("%s %d, %d", monthLabel(soldier.DeathMonth), soldier.DeathDay, soldier.DeathYear)
	}
	return fmt.Sprintf("%s %d", monthLabel(soldier.DeathMonth), soldier.DeathYear)
}

func monthLabel(month int) string {
	if month < 1 || month > 12 {
		return "Unknown"
	}
	return time.Month(month).String()
}

func imagePathForPDF(image models.Image) string {
	candidate := strings.TrimSpace(image.ResolvedPath)
	if candidate == "" {
		candidate = strings.TrimSpace(image.FilePath)
	}
	if candidate == "" {
		return ""
	}
	info, err := os.Stat(candidate)
	if err != nil || info.IsDir() || info.Size() == 0 {
		return ""
	}
	switch strings.ToLower(filepath.Ext(candidate)) {
	case ".jpg", ".jpeg", ".png", ".gif":
	default:
		return ""
	}
	return candidate
}
