// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {archive} from '../models';
import {http} from '../models';

export function ExportFullDatabasePDF(arg1:archive.PrintSettings):Promise<string>;

export function ServeHTTP(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
